### ISSUE TITLE
Updating Quota

### ISSUE THREAD

**Issue by hogendoorn** [poulpreben/veeam-cloudconnect#1]
Hi Poel Preben,

Firtst of thanks of sharing this code, i really realy appreciate it. I have been using it a lot on our company's  intranet and its working great! 

I hope you could help me with one think i can't figure out. I am trying to change a maximum quota of the tenent's repository but i can't get the xml or url right. 

Hope you can help! 

Thanks in advance 

Michael

**Comment by poulpreben** [comment]
Hi Michael,

It should be pretty simple. I added this in line 27 of veeam.class.php (specified in MB):

```
private $tenant_resource_quota  = 102400;
```

Have you tried changing this setting?

Thanks,
Preben

**Comment by hogendoorn** [comment]
Hi Poel Preben,

I'm sorry i forgot to tell you that the qouta is already set with your script. I want to change the quota after the tenent had been create is case a customor wants more space.

So people in the organisation can change this when there is need to. 

Thanks 

Michael

**Comment by hogendoorn** [comment]
Do i need to make a new request?

**Comment by poulpreben** [comment]
My apologies. I simply have not had the time to test this yet. I will get back to you ASAP.

**Comment by hogendoorn** [comment]
No problem! Thanks al ready!

**Comment by hogendoorn** [comment]
Hi Poulpreben,

Any change you already had some time for this? Have been trying to figure out for my self but haven't nailed it yet, thanks mike

**Comment by poulpreben** [comment]
Hi Mike,

I have found out how to do this. You can simulate it by going to https://enterprisemanager:9398/api and login to the web console.

Find your tenant under /cloud/tenants?format=Entity and click the Edit link for the corresponding tenant (http://i.imgur.com/SPKANTt.png).

This will create a PUT request including all your tenant's information - including resources. It is not entirely obvious, but this seems to be how it is implemented in the API for now.

I created a request looking like this:

```
<?xml version="1.0" encoding="utf-8"?>
<CloudTenant Type="CloudTenant" Href="https://10.0.0.7:9398/api/cloud/tenants/9cc5ae8a-0903-4e9b-8efc-46a921168104?format=Entity" Name="pberg" UID="urn:veeam:CloudTenant:9cc5ae8a-0903-4e9b-8efc-46a921168104" xmlns="http://www.veeam.com/ent/v1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Password/>
  <Description/>
  <Enabled>true</Enabled>
  <LeaseOptions Enabled="false"/>
  <Resources>
    <CloudTenantResource Type="CloudTenantResource" Href="https://10.0.0.7:9398/api/cloud/tenants/9cc5ae8a-0903-4e9b-8efc-46a921168104/resources/285673e0-cc76-4751-af48-580ec760fb98" Id="285673e0-cc76-4751-af48-580ec760fb98">
      <RepositoryQuota>
        <DisplayName>cloudconnect-pberg-01</DisplayName>
        <RepositoryUid>urn:veeam:Repository:38dff16b-cdfe-4c16-b605-cd788ebf7f73</RepositoryUid>
        <WanAcceleratorUid>urn:veeam:WanAccelerator:4f2d1d2c-aac3-4434-aae0-efe2eb5b805e</WanAcceleratorUid>
        <Quota>**NEW QUOTA HERE**</Quota>
        <UsedQuota>13230</UsedQuota>
      </RepositoryQuota>
    </CloudTenantResource>
  </Resources>
  <VmCount>7</VmCount>
</CloudTenant>
```

Sorry I have not had the time to implement this in my example, but this should get you going.
